Seed: 1
Initial POI Locations: null
Initial Agent Positions: null
Number of Agents: 10
Number of POIs: 5
World Width: 10
World Length: 10
Coupling: 1
Observation Radius: 3.0
Consideration Radius: 5.0
Minimum Distance: 1.0
Steps: 100
